version: '3.8'

services:
  db:
    image: postgres:15
    container_name: quest-db
    environment:
      POSTGRES_USER: quest_user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: quest_board
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: quest-backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    working_dir: /app
    env_file:
      - db.env
    command: go run main.go

  frontend:
    build: ./frontend
    container_name: quest-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: yarn dev
    depends_on:
      - backend

volumes:
  pgdata: